name: xcube-eopf
channels:
- conda-forge
dependencies:
  - python >=3.10
  # Library Dependencies
  - dask
  - numpy
  - pyproj
  - pystac
  - pystac-client
  - shapely
  - xarray
  - xarray-eopf >=0.2.0
  - xcube >=1.11.0
  - xcube-resampling
  # Development Dependencies - Tools
  - black
  - isort
  - pytest
  - pytest-cov
  - pytest-recording
  - ruff
  # Development Dependencies - Demos
  - jupyterlab
  - matplotlib
